development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: simple_development
  pool: 5
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: simple_test
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: simple_production
  