development:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: simple_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: simple_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  database: simple_production
  pool: 5
  username: root
  password:
  host: 127.0.0.1
